'use strict';
const $=id=>document.getElementById(id),model=new CreatureModel(),canvas=$('arena'),ctx=canvas.getContext('2d');
let paused=false,tool='light',speed=1,last=0,accumulator=0,showTrail=true,toastUntil=0;
const nodes=[['LL','Light L',24,38,'#bcf590'],['LR','Light R',24,98,'#bcf590'],['OL','Obstacle L',24,163,'#ffb174'],['OR','Obstacle R',24,223,'#ffb174'],['SL','Steer L',164,75,'#c7dabb'],['SR','Steer R',164,180,'#c7dabb'],['ML','Motor L',300,75,'#bcf590'],['MR','Motor R',300,180,'#bcf590']];
const edges=[[0,4,1],[0,5,-1],[1,5,1],[1,4,-1],[2,5,1],[2,4,-1],[3,4,1],[3,5,-1],[4,7,1],[4,6,-1],[5,6,1],[5,7,-1]];
const paths=edges.map(([a,b,sign])=>{const p=document.createElementNS('http://www.w3.org/2000/svg','path'),n=nodes[a],m=nodes[b];p.setAttribute('d',`M${n[2]} ${n[3]} C${n[2]+65} ${n[3]},${m[2]-65} ${m[3]},${m[2]} ${m[3]}`);p.setAttribute('stroke',a===2||a===3?'#ffb174':'#bcf590');p.setAttribute('fill','none');p.setAttribute('stroke-width','1.3');if(sign<0)p.setAttribute('stroke-dasharray','4 5');$('wires').appendChild(p);return p});
const buttons=nodes.map((n,i)=>{const b=document.createElement('button');b.className='node';b.style.left=n[2]/330*100+'%';b.style.top=n[3]/245*100+'%';b.innerHTML=n[0]+`<span class="caption">${n[1]}</span>`;b.setAttribute('aria-label',n[1]+' node');b.setAttribute('aria-pressed','true');b.title=n[1]+': click to disable';b.onclick=()=>{model.toggle(i);updateCircuit();announce(n[1]+(model.enabled[i]?' enabled':' disabled'))};$('circuit').appendChild(b);return b});
function announce(text){$('announcement').textContent=text}
function message(text){$('arenaHelp').textContent=text;toastUntil=performance.now()+2200;announce(text)}
function setTool(t){tool=t;['light','obstacle','erase'].forEach(k=>{const el=$(k+'Tool');el.classList.toggle('selected',t===k);el.setAttribute('aria-pressed',String(t===k))});$('arenaHelp').textContent=t==='light'?'Click anywhere to move the light':t==='obstacle'?'Click clear ground to add an obstacle':'Click an obstacle to remove it';toastUntil=0}
function setPaused(value){paused=value;$('pause').innerHTML=paused?'▶ <span>Resume</span>':'Ⅱ <span>Pause</span>';$('pause').setAttribute('aria-label',paused?'Resume simulation':'Pause simulation');$('liveDot').style.background=paused?'#a0afa3':'#bcf590';$('status').textContent=paused?'PAUSED':'EXPLORING';last=0}
function setMode(mode){if(!['seek','flee'].includes(mode))throw Error('Mode must be seek or flee');model.mode=mode;['seek','flee'].forEach(k=>{$(k).classList.toggle('selected',k===mode);$(k).setAttribute('aria-pressed',String(k===mode))})}
function reset(){model.reset();speed=1;showTrail=true;$('speed').value=1;$('speedLabel').textContent='1×';$('sensitivity').value=280;$('rangeLabel').textContent='280';$('trail').checked=true;$('autolight').checked=true;accumulator=0;setMode('seek');setPaused(false);setTool('light');updateCircuit();message('Fresh circuit. A new little adventure.')}
$('reset').onclick=reset;$('pause').onclick=()=>setPaused(!paused);$('seek').onclick=()=>setMode('seek');$('flee').onclick=()=>setMode('flee');$('restore').onclick=()=>{model.restore();updateCircuit();message('All eight nodes restored')};$('tryNode').onclick=()=>{if(model.enabled[0])model.toggle(0);updateCircuit();message('Left light sensor disabled. Watch its path.')};['light','obstacle','erase'].forEach(t=>$(t+'Tool').onclick=()=>setTool(t));
$('speed').oninput=e=>{speed=Number(e.target.value);$('speedLabel').textContent=speed+'×'};$('sensitivity').oninput=e=>{model.range=Number(e.target.value);$('rangeLabel').textContent=model.range};$('trail').onchange=e=>showTrail=e.target.checked;$('autolight').onchange=e=>model.autoLight=e.target.checked;
canvas.addEventListener('pointerdown',e=>{const rect=canvas.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*1000,y=(e.clientY-rect.top)/rect.height*680;canvas.focus({preventScroll:true});if(tool==='light'){if(!model.setLight(x,y))message('Place the light on clear ground')}else if(tool==='obstacle'){if(!model.addObstacle(x,y))message('Choose more space, away from the creature and light')}else if(!model.removeObstacle(x,y))message('Click directly on an obstacle')});
document.addEventListener('keydown',e=>{if(e.target.matches('input,button,summary,a'))return;if(e.code==='Space'){e.preventDefault();setPaused(!paused)}if(e.key.toLowerCase()==='r')reset();if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();model.setLight(model.light.x+({'ArrowLeft':-25,'ArrowRight':25}[e.key]||0),model.light.y+({'ArrowUp':-25,'ArrowDown':25}[e.key]||0))}});
function updateCircuit(){buttons.forEach((b,i)=>{const v=model.activity[i];b.classList.toggle('disabled',!model.enabled[i]);b.setAttribute('aria-pressed',String(model.enabled[i]));b.title=nodes[i][1]+(model.enabled[i]?': click to disable':': click to enable');b.style.background=model.enabled[i]?`color-mix(in srgb, ${nodes[i][4]} ${15+v*65}%, #152018)`:'#252b28';b.style.color=v>.5?'#142016':'#e6f1df';b.style.boxShadow=`0 0 0 5px #17201a,0 0 ${v*20}px ${nodes[i][4]}55`});paths.forEach((p,i)=>{const [a,b]=edges[i];p.style.opacity=model.enabled[a]&&model.enabled[b]?.15+.75*model.activity[a]:.06});$('leftMeter').value=model.left;$('rightMeter').value=model.right;$('leftValue').textContent=Math.round(model.left*100)+'%';$('rightValue').textContent=Math.round(model.right*100)+'%';$('active').innerHTML=model.enabled.filter(Boolean).length+' <small>/ 8</small>';$('distance').innerHTML=Math.round(model.distance).toLocaleString()+' <small>units</small>';$('reached').textContent=model.reached;$('time').textContent=Math.floor(model.time/60)+':'+String(Math.floor(model.time%60)).padStart(2,'0');if(!paused)$('status').textContent=model.contact?'TOUCHING OBSTACLE':model.mode==='seek'?'SEEKING LIGHT':'AVOIDING LIGHT'}
function circle(x,y,r,fill,stroke){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function draw(){const dpr=Math.min(devicePixelRatio||1,2),w=Math.round(canvas.clientWidth*dpr),h=Math.round(canvas.clientHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}ctx.setTransform(w/1000,0,0,h/680,0,0);ctx.clearRect(0,0,1000,680);ctx.lineWidth=1;ctx.fillStyle='#26392b';for(let x=25;x<1000;x+=25)for(let y=25;y<680;y+=25)ctx.fillRect(x,y,1.5,1.5);
 const l=model.light,g=ctx.createRadialGradient(l.x,l.y,0,l.x,l.y,175);g.addColorStop(0,'#bbf68022');g.addColorStop(1,'#bbf68000');circle(l.x,l.y,175,g);ctx.setLineDash([3,7]);circle(l.x,l.y,42,null,'#bcf59035');ctx.setLineDash([]);circle(l.x,l.y,19,'#bbf68014','#bcf59066');circle(l.x,l.y,7,'#d6ffa3');ctx.strokeStyle='#bcf590';for(let i=0;i<8;i++){const a=i*Math.PI/4;ctx.beginPath();ctx.moveTo(l.x+Math.cos(a)*25,l.y+Math.sin(a)*25);ctx.lineTo(l.x+Math.cos(a)*31,l.y+Math.sin(a)*31);ctx.stroke()}ctx.font='11px "DM Sans", sans-serif';ctx.fillStyle='#abc395';ctx.textAlign='center';ctx.fillText('LIGHT',l.x,l.y+57);
 for(const o of model.obstacles){circle(o.x+4,o.y+6,o.r+3,'#080d0980');circle(o.x,o.y,o.r,'#26352b','#52654e');circle(o.x,o.y,o.r-6,null,'#3a4c3b');ctx.save();ctx.beginPath();ctx.arc(o.x,o.y,o.r-7,0,Math.PI*2);ctx.clip();ctx.strokeStyle='#46594355';for(let k=-100;k<100;k+=13){ctx.beginPath();ctx.moveTo(o.x+k-70,o.y-80);ctx.lineTo(o.x+k+70,o.y+80);ctx.stroke()}ctx.restore()}
 if(showTrail&&model.trail.length>1){ctx.lineWidth=1.8;ctx.strokeStyle='#b9e79050';ctx.beginPath();model.trail.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}
 ctx.save();ctx.translate(model.x,model.y);ctx.rotate(model.angle);[-1,1].forEach((side,i)=>{const a=side*.65;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,82,a-.23,a+.23);ctx.closePath();ctx.fillStyle=model.enabled[i]?'#bcf5900e':'#aaaaaa05';ctx.fill();ctx.strokeStyle=model.enabled[i]?'#bcf59026':'#aaaaaa10';ctx.lineWidth=1;ctx.stroke()});
 // The creature is a schematic differential-drive agent, not a anatomical reconstruction.
 ctx.shadowColor='#bcf59055';ctx.shadowBlur=15;ctx.fillStyle='#bcf590';ctx.strokeStyle='#e9ffd4';ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(19,0);ctx.lineTo(-10,-11);ctx.quadraticCurveTo(-4,0,-10,11);ctx.closePath();ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#273c22';ctx.fillRect(-6,-4,8,8);[-1,1].forEach((s,i)=>{circle(9,s*5,2.2,model.enabled[i]?'#ffffff':'#42573d');ctx.strokeStyle='#a1be86';ctx.beginPath();ctx.moveTo(9,s*5);ctx.lineTo(20,s*14);ctx.stroke()});ctx.restore();ctx.textAlign='center';ctx.fillStyle='#d5e7c9';ctx.font='11px "DM Sans", sans-serif';ctx.fillText('LITTLE FLY',model.x,model.y+35);
}
let lastUi=0,lastReached=0;function frame(t){if(!last)last=t;const elapsed=Math.min((t-last)/1000,.1);last=t;if(!paused){accumulator+=elapsed*speed;while(accumulator>=1/120){model.step(1/120);accumulator-=1/120}}if(model.reached>lastReached){message('Light reached! '+(model.autoLight?'A new light appeared.':'Move the light to keep exploring.'))}lastReached=model.reached;if(t-lastUi>80){updateCircuit();lastUi=t}if(toastUntil&&t>toastUntil){setTool(tool)}draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_creature_experiment',description:'Set light response, pause state, or enabled circuit nodes in the visible creature simulation.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['seek','flee']},paused:{type:'boolean'},disabledNodes:{type:'array',items:{type:'integer',minimum:0,maximum:7},uniqueItems:true}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['mode','paused','disabledNodes'].includes(k))||(input.mode!==undefined&&!['seek','flee'].includes(input.mode))||(input.paused!==undefined&&typeof input.paused!=='boolean')||(input.disabledNodes!==undefined&&(!Array.isArray(input.disabledNodes)||input.disabledNodes.some(i=>!Number.isInteger(i)||i<0||i>7))))throw Error('Invalid experiment settings');if(input.mode!==undefined)setMode(input.mode);if(input.paused!==undefined)setPaused(input.paused);if(input.disabledNodes!==undefined){model.restore();input.disabledNodes.forEach(i=>{if(model.enabled[i])model.toggle(i)})}updateCircuit();return{mode:model.mode,paused,disabledNodes:model.enabled.flatMap((v,i)=>v?[]:[i])}}})).catch(()=>{})}catch{}}
